### ISSUE TITLE
Crash when starting homebridge

### ISSUE THREAD

**Issue by benbeton** [matthijs2704/homebridge-thinkingcleaner#1]
Hi,
at first, thank you for the plugin!

when adding the rommba as accessory and starting homebridge,it will crash

```
Loading legacy platform ZWayServer
Loading 1 accessories...
/usr/local/lib/node_modules/homebridge/lib/api.js:33
  if (name.indexOf('.') == -1) {
  ^
TypeError: Cannot read property 'indexOf' of undefined
   at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:33:11)
   at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:164:42)
   at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:36:38)
   at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
   at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
   at Module._compile (module.js:460:26)
   at Object.Module._extensions..js (module.js:478:10)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Function.Module.runMain (module.js:501:10)
   at startup (node.js:129:16)
   at node.js:814:3
```

any idea what can cause this?
After removing the lines, it is working fine

my config: 

``` json
"accessories": [
    {
   "platform": "Roomba",
   "name": "Staubsauger",
   "ip_address": "192.168.10.33"
    }   
   ]
```

**Comment by matthijs2704** [comment]
No problem!

Are you running the latest version of Homebridge?

**Comment by matthijs2704** [comment]
No problem!

This should be fixed in the new version 0.0.3 which is now also available on NodeJs. You can update using `npm update -g homebridge-thinkingcleaner`

**Comment by benbeton** [comment]
Hi,

seems not to be fixed, did a fresh install of homebridge and the plugin (0.0.3) unfortunately there is the same error

**Comment by matthijs2704** [comment]
Do you have any other plugins installed? What version of homebridge are you running?

I did a clean install here too and it seems to just work...

**Comment by matthijs2704** [comment]
It seems like it can't find the `name` in the config, could you check that?

**Comment by benbeton** [comment]
following plugins are installed:

http
lagacy
milight

hb version is the one from yesterday ( did a fresh install)

what do you mean with "find name", should i try another one ?

**Comment by matthijs2704** [comment]
Could you just copy and paste the whole config.json? (Of course you can remove all sensitive data from it)

**Comment by benbeton** [comment]
here you go: http://pastebin.com/fN9ynvRz

**Comment by l0ghan** [comment]
Great work :)
I have the same error but it's promising

**Comment by matthijs2704** [comment]
Found why! I made a typo in the config.... Change `platform` to `accessory` and you should be ready to go!
