### ISSUE TITLE
Timeout - reading full_status

### ISSUE THREAD

**Issue by benbeton** [matthijs2704/homebridge-thinkingcleaner#2]
Hi,

thanks for resolving issue #1 that fast! 

Unfortunately it's still not working. Homebridge is starting fine, but when I try to start the roomba noting happens.

I can see the following error in the Homebridge log:

```
[Staubsauger] Could not load full_status: timeout of 60000ms exceeded
```

The device is reachable. If you need some more information, let me know
regards

**Comment by matthijs2704** [comment]
Could you remove the IP address from the config.json and try using auto-discovery? Whose IP-address did you enter (of what device)?

**Comment by benbeton** [comment]
will try this evening, thanks. I entered the roomba's IP

**Comment by matthijs2704** [comment]
Odd, when you're sure your device is reachable, it should just load the full_status and not timeout... Could you do a ping (of that IP) on your HomeBridge device to make sure it's reachable? `ping <IP here>`

**Comment by benbeton** [comment]
when leaving the IP blank, there is a discovery running and the Roomba is discovered.

now it's working, again,  thank you
