### ISSUE TITLE
Homebridge stops working after a period of time when accessories is configured

### ISSUE THREAD

**Issue by benbeton** [matthijs2704/homebridge-thinkingcleaner#3]
Hi,

I just had the issue that Homebridge stops working after a period of time when Thinkincleaner accessorie is configured. 
First I thought the error was related to a z-wave device. But it was not. 

the dev from the z-way plugin has checked my logs and found something, that maybe could trigger the error.

link to the issue: https://github.com/SphtKr/homebridge-zway/issues/11

In the past post, https://github.com/SphtKr describes what can cause the issue. Hopefully that can help to fix this.
If you need anything, just let me know, I can send you more logs.

regards

**Comment by matthijs2704** [comment]
I doubt if that caused the issue but okay I added another check

**Comment by benbeton** [comment]
thanks, i'll check that later and keep you informed

**Comment by matthijs2704** [comment]
You can also update using npm, I also updated it there to 0.0.5

**Comment by benbeton** [comment]
thanks for this. seems that it fixed the issue!
I'm sorry for keeping you busy, but I found another bug. I'll open a new issue for this

**Comment by matthijs2704** [comment]
Okay great!
